---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family  }}.yml"


- name: run shell to change hostname
  shell: hostname '{{ hostname }}'

- name: Copy the template file to env
  template: src=network.j2 dest='{{ item }}'
  with_items: '{{ hn_file }}'
  when: ansible_os_family == 'RedHat'


- name:  Copy the template file to env
  template: src=hostname.j2 dest='{{ item }}'
  with_items: '{{ hn_file }}'
  when: ansible_os_family == 'Debian'
